/* eslint-disable @next/next/no-img-element */
"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {WalletReadyState} from "@solana/wallet-adapter-base";
import {ExternalLink,LoaderCircle,ShieldCheck,Wallet,X} from "lucide-react";
import {useAladdinWallet} from "@/app/hooks/useAladdinWallet";
import {isMobileBrowser,walletBrowseLink,walletInstallLinks} from "@/app/utils/wallet";
const preferred=["Phantom","Solflare","Backpack"] as const;
export function WalletConnectModal(){const state=useAladdinWallet(),closeRef=useRef<HTMLButtonElement>(null),{modalOpen,closeWalletModal}=state,[mobile,setMobile]=useState(false),[currentUrl,setCurrentUrl]=useState("");useEffect(()=>{setMobile(isMobileBrowser());setCurrentUrl(location.href)},[]);useEffect(()=>{if(!modalOpen)return;closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")closeWalletModal()};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[modalOpen,closeWalletModal]);const detected=useMemo(()=>new Map(state.wallets.map(option=>[String(option.name),option])),[state.wallets]);if(!state.modalOpen)return null;return <div className="walletModalBackdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)state.closeWalletModal()}}><section className="walletModal" role="dialog" aria-modal="true" aria-labelledby="wallet-modal-title"><header><div><small>SOLANA DEVNET</small><h2 id="wallet-modal-title">{state.modalReason?"Connect wallet to trade":"Connect Solana Wallet"}</h2></div><button ref={closeRef} type="button" aria-label="Close wallet selector" onClick={state.closeWalletModal}><X/></button></header>{state.modalReason?<p className="walletReason">{state.modalReason}</p>:null}<div className="walletProviderList">{preferred.map(name=>{const option=detected.get(name);if(option?.readyState===WalletReadyState.Installed)return <button type="button" onClick={()=>state.chooseWallet(option.name)} disabled={state.connecting} key={name}>{option.icon?<img src={option.icon} alt=""/>:<Wallet/>}<span><b>{name}</b><small>Detected in this browser</small></span>{state.connecting?<LoaderCircle className="spin"/>:<span className="walletReady">Connect</span>}</button>;if(mobile)return <a className="mobileWalletLink" href={walletBrowseLink(name,currentUrl)} key={name}><Wallet/><span><b>{name}</b><small>Open current Aladdin context in {name}</small></span><ExternalLink/></a>;return <a className="mobileWalletLink" href={walletInstallLinks[name]} target="_blank" rel="noreferrer" key={name}><Wallet/><span><b>{name}</b><small>Not installed</small></span><span className="walletReady">Install</span></a>})}{state.wallets.filter(option=>!preferred.includes(String(option.name) as typeof preferred[number])).map(option=><button type="button" onClick={()=>state.chooseWallet(option.name)} disabled={state.connecting} key={String(option.name)}>{option.icon?<img src={option.icon} alt=""/>:<Wallet/>}<span><b>{option.name}</b><small>Compatible Wallet Standard provider</small></span><span className="walletReady">Connect</span></button>)}</div>{state.error?<p className="walletError" role="alert">{state.error}<button type="button" onClick={()=>state.openWalletModal({reason:state.modalReason})}>Try again</button></p>:null}<footer><ShieldCheck/><span>Aladdin never asks for or stores your private key, seed phrase or recovery phrase.</span></footer></section></div>}
