"use client";
import type {AnswerMode,AuthenticatedUserProfile,ConsentSettings,LegacyAnswerMode,QuerySession,SubscriptionEntitlements} from "@/app/types/ask-aladdin";
const PROFILE="aladdin-intelligence-profile",SESSIONS="aladdin-ask-sessions",LAST_ACTIVE="aladdin-last-active";
export const defaultEntitlements:SubscriptionEntitlements={plan:"Pro",historyDays:90,queryLimit:250,historicalMatchLimit:83,exports:true,sharedWorkspaces:false};
export function normaliseAnswerMode(value:LegacyAnswerMode|string|undefined|null):AnswerMode{if(value==="Researcher"||value==="Analyst")return "Analyst";if(value==="Token Creator")return "Token Creator";return "Trader"}
function normaliseProfile(value:Omit<Partial<AuthenticatedUserProfile>,"primaryProfile"|"defaultAnswerMode">&{primaryProfile?:LegacyAnswerMode;defaultAnswerMode?:LegacyAnswerMode}):AuthenticatedUserProfile{return{id:value.id||"demo-user",primaryProfile:normaliseAnswerMode(value.primaryProfile),defaultAnswerMode:normaliseAnswerMode(value.defaultAnswerMode||value.primaryProfile),timezone:value.timezone||"Europe/London",displayName:value.displayName||localStorage.getItem("aladdin-display-name")||"La_Crrypt"}}
export function loadProfile():AuthenticatedUserProfile|null{try{const raw=localStorage.getItem(PROFILE);if(!raw)return null;const parsed=JSON.parse(raw);const profile=normaliseProfile(parsed);if(parsed.primaryProfile!==profile.primaryProfile||parsed.defaultAnswerMode!==profile.defaultAnswerMode)localStorage.setItem(PROFILE,JSON.stringify(profile));return profile}catch{return null}}
export function saveProfile(primaryProfile:AnswerMode,defaultAnswerMode=primaryProfile){const profile=normaliseProfile({id:"demo-user",primaryProfile,defaultAnswerMode,timezone:"Europe/London",displayName:localStorage.getItem("aladdin-display-name")||"La_Crrypt"});localStorage.setItem(PROFILE,JSON.stringify(profile));return profile}
function normaliseSession(value:Omit<QuerySession,"primaryProfile"|"answerMode">&{primaryProfile?:LegacyAnswerMode;answerMode?:LegacyAnswerMode}):QuerySession{return{...value,primaryProfile:normaliseAnswerMode(value.primaryProfile),answerMode:normaliseAnswerMode(value.answerMode)}}
export function loadSessions():QuerySession[]{try{const parsed=JSON.parse(localStorage.getItem(SESSIONS)||"[]");if(!Array.isArray(parsed))return[];const sessions=parsed.map(normaliseSession);if(parsed.some((item,index)=>item.primaryProfile!==sessions[index].primaryProfile||item.answerMode!==sessions[index].answerMode))localStorage.setItem(SESSIONS,JSON.stringify(sessions));return sessions}catch{return[]}}
export function saveSession(session:QuerySession){const normalised=normaliseSession(session);const next=[normalised,...loadSessions().filter(item=>item.id!==normalised.id)].slice(0,12);localStorage.setItem(SESSIONS,JSON.stringify(next))}
export function loadLastActive(){const raw=localStorage.getItem(LAST_ACTIVE);return raw?new Date(raw):new Date(Date.now()-8*60*60*1000)}
export function markActive(){localStorage.setItem(LAST_ACTIVE,new Date().toISOString())}
export function loadConsent():ConsentSettings{try{const raw=localStorage.getItem("aladdin-consent");return raw?JSON.parse(raw):{personalisation:true,memory:true,retentionDays:90,updatedAt:new Date().toISOString()}}catch{return{personalisation:true,memory:true,retentionDays:90,updatedAt:new Date().toISOString()}}}