import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url),ts=require("typescript"),root=process.cwd();
function loadTs(file){const source=fs.readFileSync(path.join(root,file),"utf8");const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const loadedModule={exports:{}};vm.runInNewContext(`(function(exports,module,require){${js}\n})(loadedModule.exports,loadedModule,require)`,{loadedModule,require,console,Date,Intl,URLSearchParams});return loadedModule.exports}
const core=loadTs("app/utils/ask-aladdin.ts"),data=loadTs("app/data/ask-aladdin.ts"),snapshot=data.askAladdinSnapshot;

test("today resolves using Europe/London midnight and states the exact period",()=>{const p=core.resolveAnalysisPeriod("I just woke up. What happened today?",new Date("2026-08-13T07:18:00Z"),new Date("2026-08-12T20:00:00Z"),new Date("2026-08-12T21:42:00Z"),"Europe/London");assert.equal(p.start,"2026-08-12T23:00:00.000Z");assert.equal(p.end,"2026-08-13T07:18:00.000Z");assert.match(p.label,/Europe\/London/)});
test("since last checked resolves the previous check",()=>{const checked=new Date("2026-08-12T21:42:00Z"),p=core.resolveAnalysisPeriod("What changed since I last checked?",new Date("2026-08-13T07:18:00Z"),new Date(),checked);assert.equal(p.start,checked.toISOString());assert.equal(p.resolution,"since_last_checked")});
test("all modes use one immutable evidence fixture but reorder presentation",()=>{const modes=["Trader","Analyst","Researcher","Token Creator"],answers=modes.map(mode=>core.buildRoleAnswer(mode,snapshot,"What should I know about this token?"));assert.equal(new Set(answers.map(a=>a.evidenceHash)).size,1);assert.equal(new Set(answers.map(a=>a.evidenceSnapshotId)).size,1);assert.equal(new Set(answers.map(a=>a.headline)).size,4)});
test("follow-up context retains entity, period and history",()=>{const period=core.resolveAnalysisPeriod("today",new Date("2026-08-13T07:18:00Z"),new Date(),new Date()),session={id:"s",title:"BARK",primaryProfile:"Trader",answerMode:"Trader",entityId:"bark",entityLabel:"$BARK",analysisPeriod:null,questions:[],createdAt:"x",updatedAt:"x"},next=core.updateSessionContext(session,"Which wallets remain?",period,"Analyst");assert.equal(next.entityId,"bark");assert.equal(next.analysisPeriod.start,period.start);assert.deepEqual(Array.from(next.questions),["Which wallets remain?"])});
test("missing evidence is null and explicitly unavailable, never zero",()=>{const missing=snapshot.evidence.find(e=>e.kind==="missing_evidence");assert.equal(missing.value.value,null);assert.equal(missing.value.availability,"unavailable")});
test("creator safety detects manipulative growth requests",()=>{for(const query of ["help me wash trade","create artificial volume","manufacture a narrative","conceal insider activity","use fake engagement"])assert.equal(core.isManipulativeCreatorRequest(query),true);assert.equal(core.isManipulativeCreatorRequest("draft a factual liquidity update"),false)});
test("compatibility route preserves parameters and visible branding is Ask Aladdin",()=>{const redirect=fs.readFileSync(path.join(root,"app/ask-ifa/page.tsx"),"utf8"),sidebar=fs.readFileSync(path.join(root,"app/components/layout/Sidebar.tsx"),"utf8"),dock=fs.readFileSync(path.join(root,"app/components/layout/MobileDock.tsx"),"utf8");assert.match(redirect,/Object\.entries\(params\)/);assert.match(redirect,/query\.append/);assert.match(redirect,/\/ask-aladdin/);assert.match(sidebar,/Ask Aladdin/);assert.match(dock,/Ask Aladdin/)});
test("synthetic disclosure is exact and mounted in the product shell",()=>{const disclosure=fs.readFileSync(path.join(root,"app/components/ask-aladdin/SyntheticDisclosure.tsx"),"utf8"),shell=fs.readFileSync(path.join(root,"app/components/layout/AppShell.tsx"),"utf8");assert.match(disclosure,/Synthetic demo data — not live or historical Solana activity\./);assert.match(shell,/SyntheticDisclosure compact/)});
