import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=process.cwd(),read=file=>fs.readFileSync(path.join(root,file),"utf8");

test("Ask Aladdin starts blank and only reopens an explicitly selected session",()=>{const page=read("app/components/ask-aladdin/AskWorkspace.tsx");assert.match(page,/requested\?getActiveInvestigation\(requested\):null/);assert.doesNotMatch(page,/const .*starters=/);assert.doesNotMatch(page,/entityId:session\.entityId\|\|"bark"/);assert.match(page,/Ask about tokens, wallets and market activity\./)});
test("deterministic intent router separates conversation from data",()=>{const router=read("app/features/ask-aladdin/routing/intent-router.ts"),runner=read("app/features/ask-aladdin/run-analysis.ts");for(const intent of ["greeting","casual","data_query","definition","follow_up","ambiguous","unsupported"])assert.match(router,new RegExp(`\\b${intent}\\b`));assert.match(router,/Hi Ola\. What would you like to investigate\?/);assert.match(router,/I’m ready\. Ask me about a token/);assert.match(runner,/has_data:false/);assert.match(runner,/\["data_query","follow_up"\]/)});
test("non-data replies omit period tables and source disclosure",()=>{const page=read("app/components/ask-aladdin/AskWorkspace.tsx"),answer=read("app/components/ask-aladdin/StructuredAnswer.tsx");assert.match(page,/turn\.answer\.has_data!==false/);assert.match(answer,/if\(structured\.has_data===false\)/);assert.match(answer,/Source: Simulated data/)});
test("workspace pages have safe back controls and clean empty states",()=>{for(const file of ["app/queries/page.tsx","app/queries/[id]/page.tsx","app/dashboards/page.tsx","app/dashboards/[id]/page.tsx","app/exports/page.tsx"])assert.match(read(file),/BackButton/);assert.match(read("app/queries/page.tsx"),/No saved queries yet\./);assert.match(read("app/dashboards/page.tsx"),/No dashboards yet\./);assert.match(read("app/exports/page.tsx"),/No exports yet\./)});
test("alerts attach context without automatically submitting",()=>{const alerts=read("app/components/intelligence/FeaturePage.tsx"),page=read("app/components/ask-aladdin/AskWorkspace.tsx");assert.match(alerts,/source=alert&alertId=/);assert.match(alerts,/Open in Ask Aladdin/);assert.match(page,/attachedContextChip/);assert.doesNotMatch(page,/if\(question\)ask\(/)});
test("profile image uses IndexedDB with validation processing and removal",()=>{const store=read("app/services/profile/profile-image-store.ts"),settings=read("app/settings/page.tsx"),account=read("app/components/account/AccountControl.tsx");assert.match(store,/indexedDB\.open/);assert.match(store,/image\/jpeg/);assert.match(store,/5\*1024\*1024/);assert.match(store,/createImageBitmap/);assert.match(settings,/accept="image\/\*"/);assert.match(settings,/Remove image/);assert.match(account,/ProfileAvatar/)});
test("global banner is removed and light status text receives explicit contrast",()=>{assert.doesNotMatch(read("app/components/layout/AppShell.tsx"),/SyntheticDisclosure/);const css=read("app/components/ask-aladdin/ask-workspace.css");assert.match(css,/data-resolved-theme="light".*\.topbar/s);assert.match(css,/\.ticker b/)});
