import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";const root=process.cwd(),read=file=>fs.readFileSync(path.join(root,file),"utf8");
test("mobile uses one Workspace drawer with Chats Queries and Tools",()=>{const workspace=read("app/components/ask-aladdin/AskWorkspace.tsx"),drawer=read("app/components/ask-aladdin/drawers/WorkspaceDrawer.tsx");assert.match(workspace,/WorkspaceDrawer/);assert.doesNotMatch(workspace,/workspaceDrawerButton left|Investigations<\/button>/);for(const tab of ["chats","queries","tools"])assert.match(drawer,new RegExp(`"${tab}"`));assert.match(drawer,/useState<Tab>\("chats"\)/)});
test("drawer preserves routes actions and focus behaviour",()=>{const drawer=read("app/components/ask-aladdin/drawers/WorkspaceDrawer.tsx");for(const route of ["/queries/","/queries","/dashboards","/exports"])assert.match(drawer,new RegExp(route.replace("/","\\/")));for(const action of ["Rename","Pin","Duplicate","Archive","Delete"])assert.match(drawer,new RegExp(action));assert.match(drawer,/aria-modal="true"/);assert.match(drawer,/event\.key==="Escape"/);assert.match(drawer,/event\.key==="Tab"/);assert.match(drawer,/aria-selected/)});
test("compact composer uses arrow send and keyboard semantics",()=>{const composer=read("app/components/ask-aladdin/composer/AskComposer.tsx");assert.match(composer,/ArrowUp/);assert.match(composer,/aria-label="Send question"/);assert.match(composer,/disabled=\{!canSend\}/);assert.match(composer,/event\.key==="Enter"&&!event\.shiftKey/);assert.doesNotMatch(composer,/>Investigate/)});
test("analytical pipeline separates planning execution interpretation formatting and follow-ups",()=>{for(const file of ["app/features/ask-aladdin/planning/query-planner.ts","app/features/ask-aladdin/execution/synthetic-executor.ts","app/features/ask-aladdin/interpretation/profile-interpreter.ts","app/features/ask-aladdin/formatting/answer-formatter.ts","app/features/ask-aladdin/follow-ups/generate-follow-ups.ts"])assert.ok(fs.existsSync(path.join(root,file)),file);const runner=read("app/features/ask-aladdin/run-analysis.ts");for(const fn of ["planAskAladdinQuery","executeSyntheticQuery","interpretDataset","formatAnalyticalAnswer","generateFollowUps"])assert.match(runner,new RegExp(fn))});
test("activity exposes one timed current operation without checklist internals",()=>{const activity=read("app/components/ask-aladdin/activity/InvestigationActivity.tsx"),runner=read("app/features/ask-aladdin/run-analysis.ts");assert.match(activity,/current=run\.events\.at\(-1\)/);assert.match(activity,/activityDotGrid/);assert.match(activity,/elapsed/);assert.match(activity,/role="status"/);assert.doesNotMatch(activity,/Investigation complete|✓|○|Evidence hash|chain-of-thought/i);for(const message of ["Understanding your question","Translating request into a data query","Engineering required features","Analysing wallet behaviour","Preparing the final table"])assert.match(runner,new RegExp(message));assert.doesNotMatch(runner,/live Solana|production indexer|real SQL|millions of live/i)});
test("duplicate submission is blocked and final result remains table first",()=>{const workspace=read("app/components/ask-aladdin/AskWorkspace.tsx"),answer=read("app/components/ask-aladdin/StructuredAnswer.tsx");assert.match(workspace,/run\.status==="running"/);assert.match(workspace,/setRun\(\{status:"complete"/);const defaultBranch=answer.slice(answer.indexOf("return <div className=\"structuredQueryAnswer\""));assert.ok(defaultBranch.indexOf("structured.direct_answer")<defaultBranch.indexOf("<QueryResultTable"));assert.ok(defaultBranch.indexOf("<QueryResultTable")<defaultBranch.indexOf("structured.profile_summary"))});
test("new mobile surfaces use semantic themes safe area and reduced motion",()=>{const css=read("app/components/ask-aladdin/ask-workspace.css");for(const token of ["var(--surface)","var(--input-bg)","var(--brand-purple)","env(safe-area-inset-bottom)","prefers-reduced-motion"])assert.match(css,new RegExp(token.replace(/[()]/g,"\\$&")));assert.doesNotMatch(css,/background:\s*(#000|#fff|black|white)/i)});
test("legacy persistence keys and routes remain unchanged",()=>{const persistence=read("app/services/workspace-local.ts"),compat=read("app/ask-ifa/page.tsx");for(const key of ["aladdin-ask-sessions","aladdin-saved-queries","aladdin-dashboards","aladdin-exports"])assert.match(persistence,new RegExp(key));assert.match(compat,/ask-aladdin/)});

test("empty screen offers Aladdin-specific investigations and anchors composer",()=>{const workspace=read("app/components/ask-aladdin/AskWorkspace.tsx"),css=read("app/components/ask-aladdin/ask-workspace.css");for(const phrase of ["Migration Specialists","profitable wallets","first-100 retention","concentration","liquidity"])assert.match(workspace,new RegExp(phrase,"i"));assert.match(workspace,/askChatViewport/);assert.match(css,/\.askChatViewport \.compactComposer/);assert.match(css,/100dvh/)});
