import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";const root=process.cwd(),read=file=>fs.readFileSync(path.join(root,file),"utf8");
test("mobile uses one narrow Ask Aladdin drawer with Chats Saved and Usage",()=>{const workspace=read("app/components/ask-aladdin/AskWorkspace.tsx"),drawer=read("app/components/ask-aladdin/drawers/WorkspaceDrawer.tsx");assert.match(workspace,/WorkspaceDrawer/);assert.doesNotMatch(workspace,/workspaceDrawerButton left|Investigations<\/button>/);for(const tab of ["chats","saved","usage"])assert.match(drawer,new RegExp(`"${tab}"`));assert.match(drawer,/useState<Section>\("chats"\)/)});
test("drawer preserves routes actions and focus behaviour",()=>{const drawer=read("app/components/ask-aladdin/drawers/WorkspaceDrawer.tsx");assert.match(drawer,/\/queries/);for(const action of ["Rename","Pin","Duplicate","Archive","Delete"])assert.match(drawer,new RegExp(action));assert.match(drawer,/aria-modal="true"/);assert.match(drawer,/event\.key==="Escape"/);assert.match(drawer,/event\.key==="Tab"/);assert.match(drawer,/aria-current/)});
test("compact composer uses arrow send and keyboard semantics",()=>{const composer=read("app/components/ask-aladdin/composer/AskComposer.tsx");assert.match(composer,/ArrowUp/);assert.match(composer,/aria-label="Send question"/);assert.match(composer,/disabled=\{!canSend\}/);assert.match(composer,/event\.key==="Enter"&&!event\.shiftKey/);assert.doesNotMatch(composer,/>Investigate/)});
test("analytical pipeline separates planning execution interpretation formatting and follow-ups",()=>{for(const file of ["app/features/ask-aladdin/planning/query-planner.ts","app/features/ask-aladdin/execution/synthetic-executor.ts","app/features/ask-aladdin/interpretation/profile-interpreter.ts","app/features/ask-aladdin/formatting/answer-formatter.ts","app/features/ask-aladdin/follow-ups/generate-follow-ups.ts"])assert.ok(fs.existsSync(path.join(root,file)),file);const runner=read("app/features/ask-aladdin/run-analysis.ts");for(const fn of ["planAskAladdinQuery","executeSyntheticQuery","interpretDataset","formatAnalyticalAnswer","generateFollowUps"])assert.match(runner,new RegExp(fn))});
test("activity exposes one timed current operation without checklist internals",()=>{const activity=read("app/components/ask-aladdin/activity/InvestigationActivity.tsx"),runner=read("app/features/ask-aladdin/run-analysis.ts");assert.match(activity,/current=run\.events\.at\(-1\)/);assert.match(activity,/activityDotGrid/);assert.match(activity,/elapsed/);assert.match(activity,/role="status"/);assert.doesNotMatch(activity,/Investigation complete|âœ“|â—‹|Evidence hash|chain-of-thought/i);for(const message of ["Resolving the question, entity and analysis period","Loading and filtering matching records","Calculating the requested features","Analysing and ranking","Preparing the final result"])assert.match(runner,new RegExp(message));assert.doesNotMatch(runner,/live Solana|production indexer|real SQL|millions of live/i)});
test("duplicate submission is blocked and final result remains table first",()=>{const workspace=read("app/components/ask-aladdin/AskWorkspace.tsx"),answer=read("app/components/ask-aladdin/StructuredAnswer.tsx");assert.match(workspace,/run\.status==="running"/);assert.match(workspace,/setRun\(completedRun\)/);const defaultBranch=answer.slice(answer.indexOf("return <div className=\"structuredQueryAnswer\""));assert.ok(defaultBranch.indexOf("structured.direct_answer")<defaultBranch.indexOf("<QueryResultTable"));assert.ok(defaultBranch.indexOf("<QueryResultTable")<defaultBranch.indexOf("structured.profile_summary"))});
test("new mobile surfaces use semantic themes safe area and reduced motion",()=>{const css=read("app/components/ask-aladdin/ask-workspace.css");for(const token of ["var(--surface)","var(--input-bg)","var(--brand-purple)","env(safe-area-inset-bottom)","prefers-reduced-motion"])assert.match(css,new RegExp(token.replace(/[()]/g,"\\$&")));assert.doesNotMatch(css,/background:\s*(#000|#fff|black|white)/i)});
test("legacy persistence keys and routes remain unchanged",()=>{const persistence=read("app/services/workspace-local.ts"),compat=read("app/ask-ifa/page.tsx");for(const key of ["aladdin-ask-sessions","aladdin-saved-queries","aladdin-dashboards","aladdin-exports"])assert.match(persistence,new RegExp(key));assert.match(compat,/ask-aladdin/)});

test("empty screen offers Aladdin-specific investigations and anchors composer",()=>{const workspace=read("app/components/ask-aladdin/AskWorkspace.tsx"),css=read("app/components/ask-aladdin/ask-workspace.css");for(const phrase of ["Migration Specialists","profitable wallets","first-100 retention","concentration","liquidity"])assert.match(workspace,new RegExp(phrase,"i"));assert.match(workspace,/askChatViewport/);assert.match(css,/\.askChatViewport \.compactComposer/);assert.match(css,/100dvh/)});
test("deep analyses use an expandable staged view while quick questions retain one-line thinking",()=>{const activity=read("app/components/ask-aladdin/activity/InvestigationActivity.tsx"),deep=read("app/components/ask-aladdin/activity/LongAnalysisProgress.tsx"),classifier=read("app/features/ask-aladdin/progress/classify-run-depth.ts");assert.match(activity,/run\.depth==="deep"/);assert.match(activity,/activityDotGrid/);assert.match(deep,/completed.*of.*total.*stages/s);assert.match(deep,/aria-expanded/);assert.match(deep,/status==="complete".*setExpanded\(false\)/);assert.doesNotMatch(deep,/Stop|cancel/i);assert.match(classifier,/migration specialists|historical|cohort|formation/i)});
test("deep progress is driven by real runner stages and persists outside legacy investigation records",()=>{const runner=read("app/features/ask-aladdin/run-analysis.ts"),store=read("app/services/analysis-run-store.ts"),workspace=read("app/components/ask-aladdin/AskWorkspace.tsx");for(const stage of ["Resolving the question, entity and analysis period","Loading and filtering matching records","Calculating the requested features","Analysing and ranking","Creating the profile-specific interpretation","Preparing the final result"])assert.match(runner,new RegExp(stage));assert.match(runner,/status:"pending"/);assert.match(store,/aladdin-analysis-run:/);assert.match(store,/interrupted before it finished/);assert.match(workspace,/classifyAnalysisRunDepth/);assert.match(workspace,/saveAnalysisRun/)});
