import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";const root=process.cwd(),read=file=>fs.readFileSync(path.join(root,file),"utf8");
test("workspace keeps legacy sessions and creates blank investigations without deletion",()=>{const source=read("app/services/workspace-local.ts");assert.match(source,/questions:Array\.isArray\(value\.questions\)\?value\.questions:\[\]/);assert.match(source,/turns:Array\.isArray\(value\.turns\)\?value\.turns:\[\]/);assert.match(source,/createBlankInvestigation/);assert.doesNotMatch(source,/localStorage\.clear/) });
test("latest and requested investigations can reopen",()=>{const service=read("app/services/workspace-local.ts"),page=read("app/components/ask-aladdin/AskWorkspace.tsx");assert.match(service,/getActiveInvestigation/);assert.match(service,/items\[0\]\|\|null/);assert.match(page,/params\.get\("session"\)/)});
test("investigation actions include rename pin archive delete and duplicate",()=>{const source=read("app/components/ask-aladdin/WorkspaceSidebar.tsx");for(const label of ["Rename","Unpin","Pin","Duplicate","Archive","Delete"])assert.match(source,new RegExp(label));assert.match(source,/confirm\(/)});
test("generated follow-ups are contextual and clickable in the same workspace",()=>{const util=read("app/utils/workspace.ts"),page=read("app/components/ask-aladdin/AskWorkspace.tsx");assert.match(util,/liquidity start falling/);assert.match(util,/bundle-linked wallets/);assert.match(util,/methodology/);assert.match(page,/generatedNextQuestions\.map/);assert.match(page,/onClick=\{\(\)=>ask\(item\)\}/)});
test("saved query dashboard and export stores are separate and linked",()=>{const source=read("app/services/workspace-local.ts");for(const key of ["aladdin-saved-queries","aladdin-dashboards","aladdin-exports"])assert.match(source,new RegExp(key));assert.match(read("app/components/ask-aladdin/WorkspaceDialogs.tsx"),/Included query/);assert.match(read("app/types/workspace.ts"),/creditCostPlaceholder/)});
test("workspace consumes the global theme without owning a selector",()=>{const page=read("app/components/ask-aladdin/AskWorkspace.tsx"),css=read("app/workspace.css");assert.doesNotMatch(page,/ThemeControl|aria-label="Theme"/);assert.doesNotMatch(css,/data-theme=light|prefers-color-scheme/)});
test("default answer hides internal identifiers and keeps detail disclosure",()=>{const source=read("app/components/ask-aladdin/AskWorkspace.tsx");assert.doesNotMatch(source,/evidenceHash|evidenceSnapshotId|immutable evidence/i);assert.match(read("app/components/ask-aladdin/StructuredAnswer.tsx"),/Data details/)});
test("responsive workspace uses drawers and controlled table scrolling",()=>{const css=read("app/workspace.css");assert.match(css,/workspaceSidebar\.open/);assert.match(css,/investigationTools\.open/);assert.match(css,/overflow-x:auto/);assert.match(css,/max-width:760px/)});
