import type {AnswerMode,LegacyAskAladdinAnswer,EvidenceSnapshot,QuerySession,ResolvedAnalysisPeriod} from "@/app/types/ask-aladdin";

const londonFormatter=(date:Date,timezone:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:timezone,timeZoneName:"short"}).format(date);
export function resolveAnalysisPeriod(query:string,now:Date,lastActive:Date,lastChecked:Date,timezone="Europe/London"):ResolvedAnalysisPeriod{
 const q=query.toLowerCase();let start:Date;let resolution:ResolvedAnalysisPeriod["resolution"];
 if(q.includes("today")||q.includes("woke up")||q.includes("overnight")){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now);const pick=(t:string)=>parts.find(p=>p.type===t)?.value||"01";const localMidnight=`${pick("year")}-${pick("month")}-${pick("day")}T00:00:00`;const offset=timezone==="Europe/London"?"+01:00":"Z";start=new Date(localMidnight+offset);resolution="today"}
 else if(q.includes("while i was away")||q.includes("last session")){start=lastActive;resolution="since_last_active"}
 else if(q.includes("since i last checked")||q.includes("last checked")){start=lastChecked;resolution="since_last_checked"}
 else{start=new Date(now.getTime()-60*60*1000);resolution="current_snapshot"}
 return{start:start.toISOString(),end:now.toISOString(),timezone,label:`${londonFormatter(start,timezone)} to ${londonFormatter(now,timezone)} ${timezone}`,resolution};
}

const e=(snapshot:EvidenceSnapshot,id:string)=>snapshot.evidence.find(item=>item.id===id)!;
const claim=(snapshot:EvidenceSnapshot,id:string,title:string,body?:string)=>({id:`claim-${id}`,kind:e(snapshot,id).kind,title,body:body||e(snapshot,id).detail,evidenceIds:[id],terminalView:e(snapshot,id).terminalView});
export function buildRoleAnswer(mode:AnswerMode,snapshot:EvidenceSnapshot,question:string):LegacyAskAladdinAnswer{
 const briefing=/woke up|today|while i was away|overnight/i.test(question);
 const commonLimitations=[e(snapshot,"bundle").limitations!,e(snapshot,"coordinated-flow").limitations!,e(snapshot,"historical").limitations!,"Synthetic observations demonstrate product behaviour and are not live market evidence."];
 const base={mode,evidenceSnapshotId:snapshot.id,evidenceHash:snapshot.hash,limitations:commonLimitations};
 if(mode==="Trader")return{...base,headline:briefing?"Market state changed while you were away":"BARK retained early-wallet support, with material liquidity and creator-flow risks",summary:"Market state, wallet flow and retention are prioritised here. This is evidence for investigation and position management, not a trading verdict.",sections:[{title:"Market state and flow",claims:[claim(snapshot,"market-cap","Current market state"),claim(snapshot,"liquidity","Liquidity changed"),claim(snapshot,"coordinated-flow","Flow sequence")]},{title:"Wallets, retention and risk",claims:[claim(snapshot,"retention","Early-wallet retention"),claim(snapshot,"migration-specialists","Migration Specialist activity"),claim(snapshot,"creator-selling","Creator-linked selling"),claim(snapshot,"concentration","Holder concentration")]},{title:"Comparable outcomes",claims:[claim(snapshot,"historical","Runner and failure comparison")]}],followUps:["Which early wallets are still holding?","Compare BARK with migrated failures.","Show creator-linked transactions."]};
 if(mode==="Analyst"){
  const researchDepth=/hypothesis|method|methodology|dataset|cohort|comparison group|confound|reproduc|provenance|research|statistical|define|definition/i.test(question);
  if(researchDepth)return{...base,headline:"Hypothesis: retained specialist participation distinguishes the runner from comparable failures",summary:"Analyst depth expanded for a methodological question. Unit of analysis: token lifecycle; the observation period, method, comparison group, provenance and coverage limits are explicit.",sections:[{title:"Hypothesis, definitions and method",claims:[claim(snapshot,"coordinated-flow","Observed sequence","Hypothesis: repeated co-buyer participation precedes broader volume and unique-buyer expansion. Unit of analysis: token lifecycle; this is descriptive and does not establish causation."),claim(snapshot,"historical","Dataset and comparison group")]},{title:"Market structure and results",claims:[claim(snapshot,"retention","Early-cohort result"),claim(snapshot,"failed-token","Comparable failure result"),claim(snapshot,"migration-specialists","Wallet-behaviour segment contribution"),claim(snapshot,"concentration","Holder structure")]},{title:"Alternative explanations and data quality",claims:[claim(snapshot,"bundle","Entity-resolution limitation"),claim(snapshot,"unknown-social","Coverage gap"),claim(snapshot,"liquidity","Liquidity confounder")]},{title:"Provenance and reproducibility",claims:[claim(snapshot,"historical","Reproducible comparison evidence","Use the cited synthetic cohort, rule version and observation timestamps to reproduce the comparison or export its evidence objects."),claim(snapshot,"coordinated-flow","Sequence provenance")]}],followUps:["Export the evidence definitions and provenance.","Show the eligible historical cohort and methodology.","Test alternative explanations without creator-linked wallets."]};
  return{...base,headline:"Post-migration participation broadened, but segment quality is uneven",summary:"A concise analytical view of lifecycle, participant composition, cohort contribution and data quality. Ask a methodological question for definitions, methods, confounders and reproducibility detail.",sections:[{title:"Lifecycle and participant composition",claims:[claim(snapshot,"migration-specialists","Specialist cohort"),claim(snapshot,"scalpers","Scalper cohort"),claim(snapshot,"fresh-wallets","Fresh-wallet cohort")]},{title:"Market structure and cohort contribution",claims:[claim(snapshot,"retention","Cohort retention"),claim(snapshot,"concentration","Supply structure"),claim(snapshot,"liquidity","Liquidity structure")]},{title:"Anomalies, alternatives and quality",claims:[claim(snapshot,"bundle","Repeated entry pattern"),claim(snapshot,"unknown-social","Coverage gap"),claim(snapshot,"historical","Comparison context")]}],followUps:["Break down net flow by participant segment.","Show methodology and reproducible evidence.","Which alternative explanations need investigation?"]};
 }
 return{...base,headline:"Attention converted into holders, but trust depends on liquidity and creator transparency",summary:"Creator mode prioritises sustainable participation and truthful communication. It does not support artificial activity or manufactured narratives.",sections:[{title:"Attention and retention",claims:[claim(snapshot,"fresh-wallets","New audience participation"),claim(snapshot,"retention","Holder conversion"),claim(snapshot,"liquidity","Liquidity health")]},{title:"Trust and concentration",claims:[claim(snapshot,"creator-selling","Creator-linked supply change"),claim(snapshot,"concentration","Concentration context"),claim(snapshot,"insider","Relationship evidence")]},{title:"Truthful communication",claims:[claim(snapshot,"historical","Evidence-backed context","Explain the verified migration, retention and liquidity changes, including limitations; do not imply historical similarity guarantees an outcome."),claim(snapshot,"unknown-social","Unsupported story elements")]}],followUps:["Draft a factual holder-retention update.","Explain token allocation transparently.","Show which claims lack evidence."]};
}

export function isManipulativeCreatorRequest(query:string){return /wash trad|artificial volume|fake engagement|hide|conceal.*insider|manufactur.*narrative|pump.*price/i.test(query)}
export function updateSessionContext(session:QuerySession,question:string,period:ResolvedAnalysisPeriod,mode:AnswerMode):QuerySession{return{...session,answerMode:mode,analysisPeriod:period,questions:[...session.questions,question],updatedAt:new Date().toISOString()}}
