"use client";import {useEffect,useState} from "react";
const groups=[{label:"PERSONAL",items:["Profile","Appearance & Language","Account & Security"]},{label:"ALADDIN",items:["Ask Aladdin & Intelligence","Integrations","Developer / API"]},{label:"SUBSCRIPTION",items:["Plan & Billing"]},{label:"SUPPORT",items:["Help & Tutorials"]}];
export default function Settings(){const [active,setActive]=useState("Profile");useEffect(()=>{const q=new URLSearchParams(location.search).get("section");if(q){const match=groups.flatMap(g=>g.items).find(x=>x.toLowerCase().startsWith(q.toLowerCase()));if(match)setActive(match)}},[]);return <><div className="pageTitle"><div><span className="eyebrow">ACCOUNT & TERMINAL</span><h1>Settings</h1><p>Human account, connected wallet and Aladdin intelligence preferences.</p></div></div><div className="settingsGrid expandedSettings"><aside>{groups.map(group=><div key={group.label}><small>{group.label}</small>{group.items.map(x=><button onClick={()=>setActive(x)} className={active===x?"active":""} key={x}>{x}</button>)}</div>)}</aside><section><h2>{active}</h2>{active==="Profile"?<Profile/>:active==="Appearance & Language"?<Appearance/>:active==="Account & Security"?<Security/>:active==="Ask Aladdin & Intelligence"?<Intelligence/>:active==="Integrations"?<Integrations/>:active==="Developer / API"?<Developer/>:active==="Plan & Billing"?<Billing/>:<Help/>}</section></div></>}
function Profile(){const [name,setName]=useState("⭕️La_Crrypt💰₿-");const [username,setUsername]=useState("ola_crrypt");useEffect(()=>{setName(localStorage.getItem("aladdin-display-name")||"⭕️La_Crrypt💰₿-");setUsername(localStorage.getItem("aladdin-username")||"ola_crrypt")},[]);function save(){localStorage.setItem("aladdin-display-name",name);localStorage.setItem("aladdin-username",username);dispatchEvent(new Event("aladdin-profile-change"))}return <div className="profileSettings"><div className="userAvatar profileAvatar">LC</div><Editable label="Display name" value={name} set={setName}/><Editable label="Username" value={username} set={setUsername}/><Editable label="Email" value="olamilekan@example.com"/><Editable label="Timezone" value="Europe/London"/><div className="connectedSummary"><small>CONNECTED TRADING WALLET</small><b>7xK...91Pd</b><strong>14.82 SOL</strong></div><button className="saveSettings" onClick={save}>Save profile locally</button><p className="settingsNote">Saved only in this browser until account backend integration.</p></div>}
function Editable({label,value,set}:{label:string;value:string;set?:(x:string)=>void}){return <label><span><b>{label}</b><small>{set?"Editable local profile value":"Account placeholder"}</small></span><input value={value} onChange={e=>set?.(e.target.value)} readOnly={!set}/></label>}
function Appearance(){const [density,setDensity]=useState("Compact");return <div className="settingSections"><h3>THEME</h3><div className="themeChoices"><button className="selected">Dark <small>Available</small></button><button disabled>Light <small>Coming soon</small></button><button disabled>System <small>Coming soon</small></button></div><SettingSelect label="Language" options={["English"]}/><SettingSelect label="Timezone" options={["Europe/London","UTC","America/New_York"]}/><SettingSelect label="Display currency" options={["USD","GBP","EUR"]}/><label><span><b>Interface density</b><small>Terminal information spacing</small></span><select value={density} onChange={e=>setDensity(e.target.value)}><option>Compact</option><option>Comfortable</option></select></label><SettingSelect label="Number formatting" options={["1.24M / 84.2K","1,240,000 / 84,200"]}/></div>}
function SettingSelect({label,options}:{label:string;options:string[]}){return <label><span><b>{label}</b><small>Local interface preference</small></span><select>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Security(){return <div className="settingSections"><Info label="Email" value="olamilekan@example.com"/><Info label="Authentication" value="Email + passkey (mock)"/><Info label="Connected wallets" value="1 wallet"/><Info label="Active sessions" value="2 sessions"/><Toggle label="Two-factor authentication"/><Info label="Last sign-in" value="London · Today 04:48"/><button className="dangerSetting">Delete account</button></div>}
function Intelligence(){return <div className="settingSections"><h3>GENERAL</h3><Toggle label="Aladdin Now visibility" on/><Toggle label="Behavioural chart annotations" on/><Toggle label="Automatic historical matching"/><SettingSelect label="Evidence density" options={["Dense","Balanced"]}/><h3>ASK ALADDIN</h3><Toggle label="Suggested follow-up questions" on/><Toggle label="Preserve session context" on/><h3>USAGE</h3><Info label="Monthly Ask Aladdin queries" value="38 / 250"/><Info label="Deep investigations" value="9 / 50"/><h3>MEMORY</h3><Toggle label="Remember searched entities" on/><Toggle label="Changed since last search" on/><SettingSelect label="Retention period" options={["30 days","90 days","Until deleted"]}/></div>}
function Integrations(){return <div className="settingSections"><h3>TELEGRAM</h3><Info label="Connection" value="Not connected"/><button className="saveSettings">Connect Telegram</button>{["Formation alerts","Profitable wallet alerts","Creator activity","Watchlist updates","Cluster activity"].map(x=><Toggle key={x} label={x}/>)}</div>}
function Developer(){return <div className="settingSections"><h3>SHARED AUTHENTICATION</h3><Info label="API key" value="alad_live_••••••••••••"/><div><button className="smallAction">Reveal</button><button className="smallAction">Rotate</button><button className="smallAction">Documentation</button><button className="smallAction">Playground</button></div><h3>ALADDIN API</h3><p className="settingsNote">Tokens · Wallets · Behaviours · Formations · Historical Matches · Launches</p><h3>ASK ALADDIN API</h3><p className="settingsNote">Ask · Sessions · Context · Historical Reasoning · Evidence Responses</p><Toggle label="Webhook delivery"/></div>}
function Billing(){return <div className="settingSections"><Info label="Plan" value="Aladdin Pro"/><Info label="Monthly price" value="$— placeholder"/><Info label="Ask Aladdin allowance" value="250 queries"/><Info label="API allowance" value="10,000 calls"/><Info label="Next billing date" value="Sep 13, 2026"/><Info label="Payment method" value="•••• 4242"/><button className="smallAction">View invoices</button><button className="smallAction">Change plan</button></div>}
function Help(){const sections={"GETTING STARTED":["Launches","Search CA","Search wallet","Terminal","Ask Aladdin","Alerts","Telegram"],"UNDERSTANDING ALADDIN":["Behaviour labels","Market Formation","First 100","Profitable Wallets","Clusters","Insider / Creator Activity","Historical Match","Data Coverage"],"DEVELOPER":["API docs","Examples","Changelog","Status"]};return <div className="helpGrid">{Object.entries(sections).map(([title,items])=><section key={title}><h3>{title}</h3>{items.map(x=><button key={x}>{x}<span>→</span></button>)}</section>)}</div>}
function Info({label,value}:{label:string;value:string}){return <p className="settingInfo"><span>{label}</span><b>{value}</b></p>}
function Toggle({label,on=false}:{label:string;on?:boolean}){const [checked,setChecked]=useState(on);return <label><span><b>{label}</b><small>Frontend preference</small></span><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/></label>}