"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ChevronDown,Coins,LogOut,User,WalletCards,X} from "lucide-react";
import {ProfileAvatar} from "./ProfileAvatar";
import {WalletBalance} from "@/app/components/wallet-connect/WalletBalance";
import {useAladdinWallet} from "@/app/hooks/useAladdinWallet";
import {ALADDIN_CREDITS} from "@/app/data/credits";
export function AccountControl(){const [open,setOpen]=useState(false),[name,setName]=useState("⭕️La_Crrypt💰₿"),[username,setUsername]=useState("ola_crrypt");const wallet=useAladdinWallet();useEffect(()=>{const load=()=>{setName(localStorage.getItem("aladdin-display-name")||"⭕️La_Crrypt💰₿");setUsername(localStorage.getItem("aladdin-username")||"ola_crrypt")};load();addEventListener("aladdin-profile-change",load);return()=>removeEventListener("aladdin-profile-change",load)},[]);return <div className="accountControl"><button className="accountTrigger" onClick={()=>setOpen(!open)} aria-expanded={open}><ProfileAvatar/><span className="accountWallet"><b>{name}</b><small>{wallet.connected?<WalletBalance/>:"Connect Wallet"}</small></span>{wallet.accountMode==="demo"?<em>DEMO</em>:null}<ChevronDown/></button>{open?<div className="accountMenu"><header><ProfileAvatar className="largeAvatar"/><div><b>{name}</b><small>@{username}</small></div><button aria-label="Close account menu" onClick={()=>setOpen(false)}><X/></button></header><section><small>TRADING WALLET</small>{wallet.connected?<><p className="walletProvider"><span>{wallet.providerName}</span><b>● DEVNET</b></p><code title={wallet.publicAddress||""}>{wallet.shortAddress}</code><p>Balance <WalletBalance refresh/></p></>:<><p className="walletDisconnected">No Solana wallet connected.</p><button className="connectFromAccount" onClick={()=>{setOpen(false);wallet.openWalletModal()}}>Connect Wallet</button></>}</section><section className="accountCredits"><small>ALADDIN CREDITS</small><strong>{ALADDIN_CREDITS.toLocaleString()} Credits</strong><Link href="/credits" onClick={()=>setOpen(false)}><Coins/>Buy Credits</Link></section><nav><Link href="/settings?section=profile" onClick={()=>setOpen(false)}><User/>Profile</Link><Link href="/settings?section=account" onClick={()=>setOpen(false)}><WalletCards/>Wallet Details</Link>{wallet.connected?<button onClick={()=>void wallet.disconnectWallet()}><WalletCards/>Disconnect Wallet</button>:null}<button onClick={()=>void wallet.signOut()}><LogOut/>Sign Out</button></nav></div>:null}</div>}
