"use client";
import Link from "next/link";
import Image from "next/image";
import {useEffect,useRef,useState} from "react";
import {Archive,Copy,Download,LayoutDashboard,Menu,Pin,Plus,Save,Search,Trash2,X} from "lucide-react";
import type {InvestigationSession,SavedQuery} from "@/app/types/workspace";

type Tab="chats"|"queries"|"tools";
const groups=["Today","Yesterday","Previous 7 days","Older"] as const;
function groupLabel(date:string){const value=new Date(date),now=new Date(),days=Math.floor((now.getTime()-value.getTime())/86400000);return days<=0?"Today":days===1?"Yesterday":days<=7?"Previous 7 days":"Older"}
function Chats({items,currentId,onNew,onOpen,onUpdate,onDelete,onDuplicate}:{items:InvestigationSession[];currentId?:string;onNew:()=>void;onOpen:(item:InvestigationSession)=>void;onUpdate:(item:InvestigationSession)=>void;onDelete:(id:string)=>void;onDuplicate:(item:InvestigationSession)=>void}){const [search,setSearch]=useState("");const filtered=items.filter(item=>item.title.toLowerCase().includes(search.toLowerCase()));return <><button className="newInvestigation" onClick={onNew}><Plus/>New investigation</button><label className="investigationSearch"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search investigations"/></label><div className="investigationHistory">{groups.map(group=>{const matches=filtered.filter(item=>item.status==="active"&&groupLabel(item.updatedAt)===group);return matches.length?<section key={group}><small>{group}</small>{matches.map(item=><article className={item.id===currentId?"active":""} key={item.id}><button onClick={()=>onOpen(item)}><b>{item.pinned&&<Pin/>}{item.title}</b><span>{item.answerMode} · {item.questions.length} questions</span></button><details><summary aria-label={`Actions for ${item.title}`}>•••</summary><div><button onClick={()=>{const title=prompt("Rename investigation",item.title);if(title)onUpdate({...item,title,updatedAt:new Date().toISOString()})}}>Rename</button><button onClick={()=>onUpdate({...item,pinned:!item.pinned,updatedAt:new Date().toISOString()})}>{item.pinned?"Unpin":"Pin"}</button><button onClick={()=>onDuplicate(item)}><Copy/>Duplicate</button><button onClick={()=>onUpdate({...item,status:"archived",updatedAt:new Date().toISOString()})}><Archive/>Archive</button><button onClick={()=>confirm(`Delete ${item.title}?`)&&onDelete(item.id)}><Trash2/>Delete</button></div></details></article>)}</section>:null})}<section><small>Archived</small>{filtered.filter(item=>item.status==="archived").map(item=><button className="archivedItem" onClick={()=>onOpen(item)} key={item.id}>{item.title}</button>)}</section></div></>}
function Queries({queries,onNavigate}:{queries:SavedQuery[];onNavigate:()=>void}){return <div className="workspaceDrawerLinks"><small>RECENT QUERIES</small>{queries.slice(0,4).map(query=><Link href={`/queries/${query.id}`} onClick={onNavigate} key={query.id}><b>{query.title}</b><span>{query.resultCount} rows</span></Link>)}{!queries.length&&<p>No saved queries yet.</p>}<Link href="/queries" onClick={onNavigate}><Menu/>View all Queries</Link><Link href="/dashboards" onClick={onNavigate}><LayoutDashboard/>Dashboards</Link><Link href="/exports" onClick={onNavigate}><Download/>Exports</Link></div>}
function Tools({session,structured,onSaveQuery,onDashboard,onExport}:{session:InvestigationSession;structured:boolean;onSaveQuery:()=>void;onDashboard:()=>void;onExport:()=>void}){const resultCount=session.turns.at(-1)?.answer.result_count||0;return <div className="workspaceDrawerTools"><button disabled={!structured} title={structured?"Save this structured result":"Ask a question that returns structured rows first"} onClick={onSaveQuery}><Save/>Save as Query</button>{!structured&&<small>Available after a structured result is created.</small>}<button disabled={!structured} title={structured?"Create from a saved structured query":"Save a structured query first"} onClick={onDashboard}><LayoutDashboard/>Create Dashboard</button><button disabled={!structured} title={structured?"Export the current rows":"No eligible rows to export"} onClick={onExport}><Download/>Export Results</button><section><small>CURRENT CONTEXT</small><p><span>Entity</span><b>{session.entityLabel}</b></p><p><span>Entity type</span><b>{session.entityType}</b></p><p><span>Analysis period</span><b>{session.analysisPeriod?.label||"Not resolved"}</b></p><p><span>Answer mode</span><b>{session.answerMode}</b></p><p><span>Timezone</span><b>Europe/London</b></p><p><span>Data freshness</span><b>2 minutes</b></p><p><span>Result count</span><b>{resultCount}</b></p></section></div>}
export function WorkspaceDrawer({open,onClose,items,currentId,queries,session,structured,onNew,onOpen,onUpdate,onDelete,onDuplicate,onSaveQuery,onDashboard,onExport}:{open:boolean;onClose:()=>void;items:InvestigationSession[];currentId?:string;queries:SavedQuery[];session:InvestigationSession;structured:boolean;onNew:()=>void;onOpen:(item:InvestigationSession)=>void;onUpdate:(item:InvestigationSession)=>void;onDelete:(id:string)=>void;onDuplicate:(item:InvestigationSession)=>void;onSaveQuery:()=>void;onDashboard:()=>void;onExport:()=>void}){const [tab,setTab]=useState<Tab>("chats"),drawerRef=useRef<HTMLElement>(null),closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();if(event.key==="Tab"&&drawerRef.current){const nodes=[...drawerRef.current.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[open,onClose]);if(!open)return null;return <div className="workspaceDrawerBackdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="workspaceDrawer" ref={drawerRef} role="dialog" aria-modal="true" aria-labelledby="workspace-title"><header><Image src="/aladdin-logo.jpg" width={28} height={28} alt=""/><b id="workspace-title">Workspace</b><button ref={closeRef} onClick={onClose} aria-label="Close workspace"><X/></button></header><div className="workspaceTabs" role="tablist" aria-label="Workspace sections">{(["chats","queries","tools"] as const).map(item=><button role="tab" aria-selected={tab===item} className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="workspaceDrawerBody">{tab==="chats"?<Chats items={items} currentId={currentId} onNew={onNew} onOpen={onOpen} onUpdate={onUpdate} onDelete={onDelete} onDuplicate={onDuplicate}/>:tab==="queries"?<Queries queries={queries} onNavigate={onClose}/>:<Tools session={session} structured={structured} onSaveQuery={onSaveQuery} onDashboard={onDashboard} onExport={onExport}/>}</div></aside></div>}
