"use client";import {useState} from "react";import {Token} from "@/app/types";import {money} from "@/app/utils/format";import {Badge} from "@/app/components/ui/Badge";import {SearchActions} from "./SearchActions";import {DataCoverage} from "./DataCoverage";import {SinceLastSearch} from "./SinceLastSearch";
const windows=["1M","5M","10M","15M","30M","1H"];
export function TokenSearchPreview({token}:{token:Token}){const [window,setWindow]=useState("5M");const lifecycle=token.migration===100?(token.age.includes("h")?"ESTABLISHED":"MIGRATED"):token.migration>0?"MIGRATING":"NEW";const status=token.id==="frog"?"insufficient":token.id==="ponk"?"outside":"validated";return <div className="entityPreview tokenPreview"><header className="entityIdentity"><span className="coin large" style={{background:token.color}}>{token.symbol[0]}</span><div><small>RESOLVED TOKEN</small><h2>${token.symbol}<em>{token.name}</em></h2><code>{token.mint.slice(0,8)}…{token.mint.slice(-4)}</code></div><Badge color={lifecycle==="MIGRATED"?"#33d6a6":"#f6b94a"}>● {lifecycle}</Badge></header><TokenMarketSummary token={token}/><div className="whatMatters"><FormationEvidence token={token} status={status}/><div className="intelSummary"><TokenProfitableWallets token={token}/><TokenFirst100Summary token={token}/><TokenConcentration token={token}/></div></div><EarlyLife token={token} selected={window} onSelect={setWindow}/><Lifecycle token={token}/><ObservedBehaviour token={token}/><DataCoverage kind="token"/><SinceLastSearch entityKey={`token-${token.id}`} current={{mc:token.mc,holders:token.holders,liquidity:token.liquidity,top10:token.top10,profitable:token.profitable,formation:token.formation}}/><SearchActions tokenId={token.id} context={`token:${token.id}`} label={`$${token.symbol}`}/></div>}
export function TokenMarketSummary({token}:{token:Token}){return <div className="entityMetrics tokenMetrics"><span><small>MARKET CAP</small><b>{money(token.mc)}</b></span><span><small>LIQUIDITY</small><b>{money(token.liquidity)}</b></span><span><small>HOLDERS</small><b>{token.holders.toLocaleString()}</b></span><span><small>AGE</small><b>{token.age}</b></span><span><small>MIGRATION</small><b>{token.migration===100?"Complete":`${token.migration}%`}</b></span><span><small>BUY / SELL</small><b>{token.buys} / {token.sells}</b></span></div>}
function FormationEvidence({token,status}:{token:Token;status:"validated"|"outside"|"insufficient"}){return <section className={`formationSummary ${status}`}><small>FORMATION · {status.toUpperCase()}</small><strong>{status==="validated"?token.formation.replaceAll("_"," "):status==="outside"?"Not classified":"Insufficient evidence"}</strong><p>{status==="validated"?"Observed participation and wallet evidence meet the current formation definition.":status==="outside"?"First observed FDV is outside the validated formation universe.":"Launch wallet history is incomplete."}</p></section>}
export function TokenProfitableWallets({token}:{token:Token}){return <span><small>PROFITABLE WALLETS</small><b>{token.profitable} entered · {Math.max(1,token.profitable-2)} holding</b></span>}
export function TokenFirst100Summary({token}:{token:Token}){return <span><small>FIRST 100</small><b>{token.retention}% holding</b></span>}
export function TokenConcentration({token}:{token:Token}){return <span><small>TOP 10</small><b>{token.top10}% supply</b></span>}
function EarlyLife({token,selected,onSelect}:{token:Token;selected:string;onSelect:(x:string)=>void}){const idx=windows.indexOf(selected);const factor=[.62,.74,.81,.87,.92,1][idx];return <section className="earlyLife"><header><span>EARLY LIFE</span><div>{windows.map(w=><button className={selected===w?"active":""} onClick={()=>onSelect(w)} key={w}>{w}</button>)}</div></header><div className="earlyGrid"><span><small>WINDOW</small><b>{selected}</b></span><span><small>FDV</small><b>{money(token.mc*factor)}</b></span><span><small>RETURN</small><b>{factor.toFixed(2)}x</b></span><span><small>VOLUME</small><b>{money(token.volume*factor)}</b></span><span><small>HOLDERS</small><b>{Math.round(token.holders*factor)}</b></span><span><small>DRAWDOWN</small><b className="sell">−{Math.round((1-factor)*100)}%</b></span></div></section>}
function Lifecycle({token}:{token:Token}){const steps=[["Launch",true],["Migration",token.migration===100],["$100K",token.mc>=100000],["$500K",token.mc>=500000],["Current",true]] as const;return <section className="lifecycle"><small>LIFECYCLE / SURVIVAL</small><div>{steps.map(([name,done],i)=><span key={name} className={done?"done":""}><i>{done?"✓":"—"}</i><b>{name}</b>{i<steps.length-1&&<em/>}</span>)}</div><p>{token.migration===100?"Migration observed · later milestones shown only where available.":"Migration milestone not yet reached."}</p></section>}
function ObservedBehaviour({token}:{token:Token}){const labels=token.retention>75?["Strong Holder Growth","Volume Expansion","Survived Early Stage"]:["High Drawdown","Early Participation","Concentration Elevated"];return <section className="observedBehaviour"><small>OBSERVED BEHAVIOUR</small><div>{labels.map((x,i)=><span key={x}><i style={{background:i===0?"#f6b94a":"#9b7cff"}}/>{x}</span>)}</div></section>}